[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[context.production.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
